<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="D:\LeonardoBS\POE\Program.cs" Link="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JogoRun\JogoRun.csproj" />
  </ItemGroup>

</Project>
